### ISSUE TITLE
Firebase authentication and mysql

### ISSUE THREAD

**Issue by senner007** [HackYourFuture-CPH/FP-class11#18]
Firebase for authentication with backend verification.
Pretty much all of it explained in this article. 
https://dev.to/emeka/securing-your-express-node-js-api-with-firebase-auth-4b5f

Mysql is then used for the content db. 
Alternatively we could use what they call Realtime database, which is more than a db. Built-in Websockets and I believe hardbound to the authentication system, afaik 🤔

**Comment by dpfernandes** [comment]
Create authentication based @senner007's video with a firebase and react example.
https://1drv.ms/v/s!AoI-8hQGtXUmnH6BnMzKNhd5uNci?e=ppJwdQ
It is using this repo :
https://github.com/senner008/Firebase-React-Express.git
so start by cloning this.
Also check out the resources for links to docs on firebase
https://github.com/HackYourFuture-CPH/React/tree/class11/resources

Use the LoginForm component on the LoginPage -  check here https://github.com/HackYourFuture-CPH/FP-class11/issues/1
