### ISSUE TITLE
New endpoint to extend the Endpoint to Get All Batches

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/FP-class11#188]
The endpoint to get all batches only returns the **ID** and the **Company_Name** and in order to populate this list we need to **create another endpoint ** with the few other new fields 

![image](https://user-images.githubusercontent.com/6642037/79751986-d20e6f00-8313-11ea-8de1-ad0f8293e3a5.png)

The new endpoint should return a list of all the batches with the following information
BATCH_ID, 
CROP_NAME, 
CUSTOMER_NAME.
STATUS,
CURRENT_STAGE,
SEEDING_POTS,
and
SEEDING_DATE

You should make sure that this endpoint is documented on SWAGER

**Comment by orhantoy** [comment]
Currently reviewing the related PR with @ricardoaguiar and I was wondering why a new endpoint is needed. It seems like it is because the data returned by `GET /api/batches` is not sufficient. Was it considered to have a `?detailed=true` query parameter instead perhaps?
