### ISSUE TITLE
Knex Migrations for batches related tables

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/FP-class11#60]
Create the Knex Migrations in order to create the DB schema for the following tables:

Table batches
Table batch_areas
Table batch_area_crop_stages 
Table batch_area_status
Table batch_area_nonreusable_resource_consumption

**Comment by amjadiftikhar** [comment]
batch_area_crop_stages was assigned to us (Adil, me and Axel) and it has already been created.
